<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2020/11/30 10:55:46

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=45.117.169.145;port=3306;dbname=hondamient_hrm;charset=utf8mb4',
  'username' => 'hondamient_hrm',
  'password' => 'Cmu#2015',
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
